# Generated by Django 2.0.5 on 2018-06-17 08:22

from django.db import migrations, models
import djongo.models.fields
import vegetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=vegetable.models.title, model_form_class=vegetable.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=vegetable.models.title, model_form_class=vegetable.models.titleForm, null=True)),
            ],
        ),
    ]
